apiVersion: apps/v1
kind: Deployment
metadata:
        name: opensource
        labels:
        app: opensource
spec:
        replicas: 3
        strategy:
        type: Recreate
        selector:
        matchLabels:
        app: opensource
...
template:
        metadata:
                labels:
                app: opensource
                tier: opensource
        spec:
                containers:
                - name: opensource
                image: tlsaudwl/opensource:latest
                imagePullPolicy: Always
                ports:
                - containerPort: 5000
                name: opensource
---
apiVersion: v1
kind: Service
metadata:
        name: opensource
        labels:
        app: opensource
spec:
ports:
        - port: 80
        targetPort: 5000
        selector:
        app: opensource
        tier: opensource
        type: LoadBalancer
